### ISSUE TITLE
link existing project into generated solution

### ISSUE THREAD

**Issue by xoorath** [premake/premake-4.x#11]
Hey,

Really sorry if this is documented, I couldn't for the life of me find out if this is or isn't possible....

I have a project file generated by another build system in a project, and I'd like to know if it's possible to link that project into the solution I generate with premake?

Specifically I'm generating a vs2015 project of a dependency GYP, and I'd like to be able to manage this from the VS2017 solution I generate with premake4.

If I have to downgrade one or upgrade the other to make them match, I can live with that so long as it's possible. If this isn't possible at all, that's fine too - would just be good to know!

Thanks :) 👍

**Comment by samsinsane** [comment]
I don't believe so - Premake5 has the concept of `externalproject` which according to the [wiki](https://github.com/premake/premake-core/wiki/externalproject) was added in Premake5, so you could update to Premake5 and take advantage of this system.
