### ISSUE TITLE
Add bazel action

### ISSUE THREAD

**Issue by erenon** [premake/premake-4.x#12]
Bazel is a powerful build system made by Google: https://bazel.build/
Is it planned to support it, by adding a Bazel action?
If not, would be the contribution of such an action accepted? Before acceptance, how is an action is tested for correctness?

Bazel uses BUILD files to describe the project. The same action logic could be used to support Facebooks build system, Buck, which uses BUCK files, which shares the syntax and semantics.

**Comment by starkos** [comment]
Contributions are always welcome, but [we're all over here now](https://github.com/premake/premake-core), working on Premake 5.x
