### ISSUE TITLE
Fails to generate output with error about lua

### ISSUE THREAD

**Issue by riban-bw** [premake/premake-4.x#17]
Running precompiled Windows version of premake with a simple target, e.g.

`premake codeblocks`

gives an error:

`No Premake script (premake4.lua) found!`

**Comment by starkos** [comment]
Is there a file named "premake4.lua" in the current working directory?

**Comment by riban-bw** [comment]
No! I started with the [quick start wiki page](https://github.com/premake/premake-4.x/wiki/Premake_Quick_Start) which just says to run the command with an action and does not mention the need to first craft a configuration. I would recommend adding reference to this step / requirement to the wiki.

**Comment by starkos** [comment]
If you're just getting started with Premake, you should switch over to [Premake5](https://github.com/premake/premake-core). This 4.x version is no longer actively maintained.

But to answer your initial request: That quick start is for people who downloaded an existing Premake-enabled project and need to generate the project files for their toolsets. The last line on that page is what you were looking for: *"To learn how to use Premake for your own software projects see [Scripting With Premake](https://github.com/premake/premake-4.x/wiki/Scripting-With-Premake)."*

**Comment by riban-bw** [comment]
The link at the end of the page does not work :-(.

I looked at v4 because v5 does not support CodeBlocks and is marked as "alpha". V4 is marked as stable. If v4 is deprecated then maybe the docs should be updated to reflect this. Also a roadmap indicating when other IDEs are likely to be supported would be good.
It would be good to have a landing place / entry point to the project that clearly steered new users to the docs they need.
I now understand that premake needs a configuration to work but it wasn't clear from the introductory docs and so negatively impacted my first impression. I am sure you want us all to have positive experience :-).

**Comment by starkos** [comment]
Those sound like nice additions, thanks for volunteering!
