### ISSUE TITLE
premake4 required to make premake4

### ISSUE THREAD

**Issue by egberts** [premake/premake-4.x#6]
In https://github.com/premake/premake-4.x/blob/master/BUILD.txt, a mere mention of the following:

```
 If you pulled the sources from BitBucket, you'll need to generate your
 own project files before you can build.
```

when I pulled it from GitHub...  too bad, we can't find the build subdirectory.

premake4 cannot be built as downloaded into a CentOS 6.5 without intensive out-reach to pull in packages to build this.

A non-starter, no?

**Comment by starkos** [comment]
You would need to download a source code package, which does include the `build/` folder with regenerated project files. You can [download a source package from SourceForge](https://sourceforge.net/projects/premake/files/Premake/4.4/).

If you're just getting started with Premake, you should probably start with version 5 though, [homepage here](http://premake.github.io).

**Comment by assarbad** [comment]
@egberts no idea which exact platform you're on, but for Windows I do provide code-signed binaries [over here](https://bitbucket.org/windirstat/premake-stable/downloads) (it's a friendly fork of premake4).
